# Generated by Django 5.2.3 on 2025-10-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_takes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество заказов книги'),
        ),
    ]
