# Generated by Django 5.2.3 on 2025-10-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_number_of_takes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='number_of_takes',
            new_name='orders_count',
        ),
    ]
