# Generated by Django 5.2.3 on 2025-10-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_number_of_takes_book_orders_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='orders_count',
        ),
    ]
